### ISSUE TITLE
File "datatype.yaml" could not be found

### ISSUE THREAD

**Issue by mkp-emde** [kae-made/dtdl-schema-generator#1]
Hello there,
I am trying to use this great tool for translating a BridgePoint-model to DTDL. My aim is to create an "Azure Digital Twins" graph.

I already created a simple xtuml-model and set the paths in [] correspondingly. But at the time of execution the following exception is thrown:

_**System.IO.FileNotFoundException**
  HResult=0x80070002_
  _**Message** = Could not find file 'C:\Users\...\dtdl-schema-generator\DTDLSchemaGeneration\ConsoleAppDTDLGenerator\bin\Debug\net5.0\datatype.yaml'._
  _**Source** = System.Private.CoreLib_
  _**Stack:**
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at Kae.XTUML.Tools.CIModelResolver.OOAofOOAModelBuilder.LoadDataTypeDef(String yamlFilePath)
   at Kae.XTUML.Tools.CIModelResolver.ConceptualInformationModelResolver.LoadOOAofOOA(String datatypeDefFilePath, String metaModelFilePath)
   at Kae.XTUML.Tools.Generator.DTDL.DTDLGenerator.LoadMetaModel() in C:\Users\...\dtdl-schema-generator\DTDLSchemaGeneration\Kae.XTUML.Tools.Generator.DTDL\DTDLGenerator.cs: Line67
   at ConsoleAppDTDLGenerator.Program.Work() in C:\Users\...\dtdl-schema-generator\DTDLSchemaGeneration\ConsoleAppDTDLGenerator\Program.cs: Line52
   at ConsoleAppDTDLGenerator.Program.Main(String[] args) in C:\Users\...\dtdl-schema-generator\DTDLSchemaGeneration\ConsoleAppDTDLGenerator\Program.cs: Line24_

---

**Note:** I didn't give the optional parameter "--meta-datatype"
* so in the method "modelResolver.LoadOOAofOOA()" the parameter "MetaDataTypeDefFilePath" is null.
https://github.com/kae-made/dtdl-schema-generator/blob/bccf5e2e7eed8177440d7cc40c4ed335e5f123ac/DTDLSchemaGeneration/Kae.XTUML.Tools.Generator.DTDL/DTDLGenerator.cs#L67
* then inside of the method "modelResolver.LoadOOAofOOA()" the default filepath "datatype.yaml" is being used. But apperently this file does not exist, which is why the exception is thrown.

I hope someone can give me a hint what to do for successfully generating DTDL.

---
Additional Information:
OS: Windows 10 (Version 21H2)
IDE: Visual Studio 2022 (Version 17.3.4)
installed dotnet-versions: .NET 5.0 Runtime (No Support); .Net 6.0 Runtime (LTS); .NET Framework 4.8 SDK; .Net SDK

**Comment by kae-made** [comment]
Thank you for your trying my tool.
I checked version integrity of related libraries and verified that it works correctly.
Please give it a try.
